swagger: '2.0'
info:
  title: ThreatRate 2
  version: 2.0.0
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  '/countriesByKidnap/{from}/{to}/':
    get:
      description: >-
        Returns countries filtered by 'kidnap' event type with various
        filtering, ordering and output settings. The endpoint serves big amount
        of  charts.
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/top'
        - name: filter
          type: string
          in: query
          required: false
          enum:
            - children
            - adults
            - locals
            - foreigners
          description: Filters initial data by one of predefined (in the enum) category.
        - name: orderBy
          type: string
          in: query
          enum:
            - kidnap
            - duration
            - ransom
          default: kidnap
          required: false
          description: >-
            Is important to sort the output set by this parameter before taking
            top (first) items in case of defined '#/parameters/top' parameter.
            If not defined, the data is sorted by kidnap amount per country.
        - name: include
          type: array
          collectionFormat: csv
          in: query
          items:
            type: string
          required: false
          enum:
            - duration
            - ransom
            - locations
            - males
            - females
          description: >-
            Coma delimited array. Defines which additional data/properties
            should be returned with basic data (read response additional fields
            description). In cae of 'locations' value, only three top location
            are returned (ordered by the highest value).
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 234
                name: can
                title: Canada
                duration: 9
                ransom: 2
                locations:
                  - value: 110
                    title: Ottawa
                  - value: 92
                    title: Vancouver
                  - value: 12
                    title: Toronto
                males: 145
                females: 89
              - value: 150
                name: etc...
  '/monthsByKidnap/{from}/{to}/':
    get:
      description: >-
        Returns fixed set of months (12) filtered by 'kidnap' event type. Sorting by months common order.  
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 130
                name: jan
                title: January
              - value: 73
                name: feb
                title: February
                
  '/locationsByKidnap/{from}/{to}/':
    get:
      description: >-
        Returns fixed set of locations (places/spots) filtered by 'kidnap' event
        type with various filtering, ordering and output settings.
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
        - name: include
          type: array
          collectionFormat: csv
          in: query
          items:
            type: string
          enum:
            - male
            - female
          required: false
          description: >-
            Coma delimited array. Defines which additional data/properties
            should be returned with basic data (read response additional fields
            description).
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 130
                name: home
                title: Home
                percentage: 0.15
                males: 80
                females: 50
              - value: 73
                name: hotel
  '/ageGroupsByKidnap/{from}/{to}/':
    get:
      description: >-
        Returns accumulated 'kidnap' event amount groupped by fixed set of age
        groups. (Sorted from 'younges' to 'oldest'). (Enum values '1-10',
        '11-18', '19-25', '26-35', '36-65', '66-up')
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
        - name: include
          type: array
          collectionFormat: csv
          in: query
          items:
            type: string
          required: false
          enum:
            - duration_range
            - ransom_range
          description: >-
            Coma delimited array. Defines which additional data/properties
            should be returned with basic data ('duration_range' and
            'ransom_range' differ from 'duration' and 'ransom' (not like for
            other similar endpoints)).
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 5
                name: 1-10
                title: 1-10 years
                duration_range:
                  from: 50
                  to: 55
                ransome_range:
                  from: 0.5
                  to: 2
              - value: 15
                name: 11-18
  '/profsByKidnap/{from}/{to}/':
    get:
      description: >-
        Returns accumulated 'kidnap' event amount groupped by fixed set of
        professional groups. (Sorted by kidnap event value).
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 7
                name: ngo
                title: NGO
                duration_range:
                  from: 50
                  to: 55
                ransome_range:
                  from: 0.5
                  to: 2
              - value: 15
                name: 11-18
  '/regions/{from}/{to}/':
    get:
      description: >-
        Returns accumulated amount of the event requested in 'filter' param
        groupped by fixed set of regions. (Sorted by 'value'). (Enum values are
        standard accross the requests. The enum defined in
        '#parameters/region').
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - name: filter
          type: string
          in: query
          required: false
          enum:
            - kidnap
            - vechicle
          default: kidnap
          description: Filters initial data by one of predefined (in the enum) category.
        - name: include
          type: array
          collectionFormat: csv
          in: query
          items:
            type: string
          required: false
          enum:
            - single
            - multi
            - duration_range
            - ransom_range
          description: >-
            Coma delimited array. Defines which additional data/properties
            should be returned with basic data ('duration_range' and
            'ransom_range' differ from 'duration' and 'ransom' (not like for
            other similar endpoints)).
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 155
                name: namerica
                title: America
                single: 100
                multi: 55
                duration_range:
                  from: 12
                  to: 20
                ransome_range:
                  from: 0.5
                  to: 2
              - value: 15
                name: samerica
  '/countries/{from}/{to}/':
    get:
      description: >-
        Returns accumulated amount of the event requested in 'filter' param
        grouped by contry returned. (Sorted by 'value' (total)).
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - name: filter
          type: string
          in: query
          required: false
          enum:
            - kidnap
            - vechicle
            - unrest
            - suicide
            - kidnap_victims_killed
          default: kidnap
          description: Filters initial data by one of predefined (in the enum) category.
        - name: include
          type: array
          collectionFormat: csv
          in: query
          items:
            type: string
          required: false
          enum:
            - unrest_categories
          description: >-
            Should be included only when 'unrest' filter is applied (otherwise
            it has no sense). Categores should present even with empty data (per
            category).
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 267
                name: bur
                title: Burundi
                unrest_categories:
                  - value: 40
                    name: terrorism
                    title: Terrorism
                  - value: 15
                    name: rebel
                    title: Rebel Activity
                  - value: 27
                    name: racial
                    title: Racially Motivated
              - value: 290
                name: yem
  '/attacksTypes/{from}/{to}/':
    get:
      description: >-
        Returns accumulated amount (incl. in percentage) of the events groupped
        by fixed set of terrorist attack types. (Sorted by 'value'). Attacks
        types set should always present even if no data per type found.
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 250
                percentage: 0.45
                name: hijaking
                title: Hijaking
              - value: 27
                percentage: 0.08
                name: wmd
  '/yearsByKidnapResult/{from}/{to}/':
    get:
      description: >-
        Returns accumulated amount of the events groupped by year and predefined
        set of kidnap result types ('killed', 'released', 'escaped', 'rescued').
        Ordered by year (recent-oldest).
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/region'
        - $ref: '#/parameters/country'
      responses:
        '200':
          description: >-
            A standard response with additional fields/collections per data
            objects.
          schema:
            $ref: '#/definitions/StandardDataResponse'
          examples:
            result:
              - value: 85
                name: 2015
                title: '2016'
                data:
                  - value: 15
                    name: killed
                    title: Killed
                  - value: 20
                    name: released
                    title: Released
                  - value: 25
                    name: escaped
                    title: Escaped
                  - value: 25
                    name: resqued
                    title: Resqued
              - value: 2016
                name: 2015
parameters:
  from:
    name: from
    in: path
    type: string
    required: true
    description: >-
      Format - 'YYYYMM' (or 'YYYY' for some cases). Date of start of filtered
      period. Potentially can be optional (in that case with 'to' parameter as
      well) if backend processing speed allows that (due to big amount of data).
  to:
    name: to
    in: path
    type: string
    required: true
    description: >-
      Format - 'YYYYMM' (or 'YYYY' for some cases). Date of end of filtered
      period. In case if omitting the last date (year/month) expect to be
      current month/year. Data of the month/year defined must be included into
      results returned.
  top:
    name: top
    in: query
    type: integer
    default: 200
    required: false
    description: >-
      If provided, defines maximum amount of items to be returned ordered
      default value param (or the one defined by 'orderBy').
  region:
    name: region
    in: query
    type: string
    required: false
    enum:
      - namerica
      - samerica
      - europe
      - asia
      - africa
      - australia
    description: 'If provided, the result must include data on all countries of this region.'
  country:
    name: country
    in: query
    type: integer
    required: false
    enum:
      - country predefine codes
    description: >-
      If provided, the result must include data on particular country only. In
      case if 'region' parameter is also provided, only 'country' is uesd.
definitions:
  StandardResponse:
    type: object
    properties:
      result:
        type: object
        description: Container for main data returned.
      lib:
        type: object
        description: >-
          A library with any additional data available. Can be empty if no
          special data returned.
        properties:
          title:
            type: string
      status:
        type: string
        description: >-
          Is mostly "success" for 200 status response. Might contain "warning"
          sometimes.
        enum:
          - success
          - warning
          - error
      message:
        type: string
        description: >-
          A message of error in case of "error" status. Or additional info for
          200.
      code:
        type: integer
        description: Code error in case of "error" response.
    required:
      - status
      - result
  StandardDataResponse:
    allOf:
      - $ref: '#/definitions/StandardResponse'
      - properties:
          result:
            type: array
            items:
              $ref: '#/definitions/StandardValue'
  StandardValue:
    type: object
    properties:
      value:
        type: string
        description: A numeric/string value if exists.
      name:
        type: string
        description: >-
          Optional field for specific data. For instance if the returning item
          is a part of some library (like cities) (the library can be also
          included in 'lib' set of the result. (For instance, the city returned
          would provide its name value for further using).
      title:
        type: string
        description: Main value for representing titling of a data node.
      percentage:
        type: number
        format: float
        description: Main value for representing of numeric percentage (not value!)
      group:
        type: string
        description: >-
          Optional field for specifying if the value belongs to any of groups
          defined in
    required:
      - title
